# New line at the start of the prompt?
add_newline = true
# Default format included for reference
format = """$os$all"""

right_format = """$cmd_duration$conda$time"""

continuation_prompt = "[‚ùØ‚ùØ](green) "
command_timeout = 1500

[username]
disabled = false
style_user = "bold cyan"
show_always = true
format = "[$user]($style) "

[hostname]
ssh_only = true
style = "bright-red"
disabled = false
format = "[$hostname]($style)  "

[directory]
truncate_to_repo = false # true
truncation_length = 3
truncation_symbol = "../"
style = "cyan"
before_repo_root_style = "dimmed cyan"
repo_root_style = "bold cyan"

# Replace the "‚ùØ" symbol in the prompt with "‚ûú" // maybe ‚îî‚îÄ>
[character]
format = " $symbol"
#success_symbol = "[‚ûú](bold green)"
success_symbol = ""
error_symbol = "[‚úñ](bold red) "

[shell]
disabled = false
format = "$indicator"
bash_indicator = "[bash ‚ùØ](bold white)"
fish_indicator = "[üêü ‚ùØ](blue)"
powershell_indicator = "ps_"
#zsh_indicator = "[‚ûú ](bright-green)"
zsh_indicator = "[‚ùØ](green)"
unknown_indicator = "mystery shell"

[shlvl]
disabled = false
format = "\\[$shlvl\\] "
threshold = 3

# Disable any .js file triggering it
[nodejs]
disabled = false
detect_extensions = ["mjs", "cjs", "ts"]

[time]
disabled = true
style = "blue"
time_format = "%H:%M"
format = " üïô [\\[$time\\]]($style)"

[rlang]
disabled = false
format = "w/ [$symbol($version)](bold bright-blue) "
# symbol = "R "
symbol = "Û∞´ø "
# Disable .Rprofile detection due to home dir
#detect_files = ["DESCRIPTION", "renv.lock"]
#detect_files = ["!$HOME/.Rprofile"] # no longer needed it seems
#detect_extensions = ["Rd", "Rmd", "Rproj"]
version_format = "${raw}"

# [custom.rpkg]
# description = "R package version"
# #command = "sed -n '/^Version:/,/([0-9]+\\.)/p' DESCRIPTION "  # shows output of command
# command = "sed -n -e 's/^Version: //p' DESCRIPTION"
# detect_files = ["DESCRIPTION"]
# #when = """ test "$HOME" == "$PWD" """
# #detect_extensions = ["R", "Rd", "Rmd", "Rproj"]
# format = "üì¶ [v$output]($style) "
# style = "bold bright-blue"
# disabled = true

# package module appears to also pick up DESCRIPTION files so no need for custom module
[package]
disabled = false

[custom.renv]
description = "renv.lock R version"
command = 'jq -r ".R.Version" renv.lock'
detect_files = ["renv.lock"]
format = "renv [$output]($style) "
style = "bold bright-blue"

[custom.rproject]
description = "rproject version for rv"
command = "awk -F'\"' '/r_version/{print $2}' rproject.toml"
detect_files = ["rproject.toml"]
format = "rv [$output]($style) "
style = "bold bright-blue"



[conda]
format = "[$symbol$environment]($style)"
style = "green"
symbol = "üÖí "
ignore_base = true

[jobs]
symbol = "+ "
threshold = 1

[os]
format = "[$symbol]($style) "
style = "bold white"
disabled = false

[os.symbols]
Windows = "Óò™ "
Macos = "ÔÖπ" # This is the NF version, which is fine I guess
Ubuntu = "\uf31b"
FreeBSD = "\ueb99"
Raspbian = "\uf315"
Linux = "\uebc6"

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '
ignore_branches = ['main']

[docker_context]
disabled = true
